### ISSUE TITLE
CLI Subscription Endpoint Incorrect

### ISSUE THREAD

**Issue by ryanking1809** [graphcool/cli#134]
The subscription endpoints displayed in the CLI are incorrect and are not as displayed at www.graph.cool
![screen shot 2017-08-01 at 8 49 58 pm](https://user-images.githubusercontent.com/5112263/28823257-05a09096-7700-11e7-9f36-99fea75ba3fb.png)

![screen shot 2017-08-01 at 8 52 20 pm](https://user-images.githubusercontent.com/5112263/28823256-05a08cea-7700-11e7-8abd-dc870789eacc.png)

**Comment by marktani** [comment]
That's still the case on latest beta, and causes a lot of confusion 🙂  For both AP/US projects.
