### ISSUE TITLE
Print auth url when authenticating

### ISSUE THREAD

**Issue by schickling** [graphcool/cli#170]
Some environments ([see this SO question](https://stackoverflow.com/questions/46065732/c9-ide-and-graphcool-issue) don't support the `open(url)` workflow, so additionally there should be printed a URL like the following:

```
Open the following URL in your browser if it doesn't open automatically:
https://console.graph.cool/...
```

**Comment by kbrandwijk** [comment]
I had the same thing on Cloud9, but I went for `gc -auth`.
Actually, I think there should be a command-line login (like github does for example)
