### ISSUE TITLE
[1.3.13] Allow supplying only deltas in module type definitions

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/cli#201]
I have a module that adds a field to user. I want to define my types.graphql as:

```graphql
type User implements Node {
  myNewField: String!
}
```

This currently throws an error when deploying, even if I also specify the required fields (id, *at)

**Comment by timsuchanek** [comment]
Thanks for bringing this up! Do you refer to "extending" the user type?
We eventually want to support extending, but that should then rather be written with the `extends` primitive of GraphQL

**Comment by kbrandwijk** [comment]
Good point about the extends syntax, that should definitely be used. However, when dropping the default system type User, a module cannot blindly expect the User Type to exist, so that syntax needs some thinking.

**Comment by marktani** [comment]
> a module cannot blindly expect the User Type to exist

But the developer could make sure it does. If not, he would get an error message when adding the module 'User type does not exist yet'.

Anyway, I prefer merging instead of extending, so types and fields on a type of a module would be combined in an additive way to the base project.

**Comment by marktani** [comment]
I created this feature request to discuss this further: https://github.com/graphcool/graphcool/issues/605.
