### ISSUE TITLE
[1.3.13] No help text for 'module add'

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/cli#204]
If I use `gc help module` it tells me:
`get help with graphcool help module COMMAND`

However, `gc help module add` shows the exact same help message.

**Comment by kbrandwijk** [comment]
Well, it turns out there is a help text, but the syntax is different:
`gc help module:add`, so the help text for `gc help module` is wrong.

**Comment by timsuchanek** [comment]
Closed in the latest beta
