### ISSUE TITLE
[1.3.13] gc pull creates a folder named '-p'

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/cli#221]
In an empty folder:
`gc env:set -e dev -p cj7gqdkrq0iz70114pgw68fuq`
`gc pull -e dev`

![image](https://user-images.githubusercontent.com/852069/30300000-a36b7508-9752-11e7-9610-130de239a8de.png)

**Comment by timsuchanek** [comment]
Fixed in latest beta
