### ISSUE TITLE
[1.3.13] Default permissions created when permissions not specified in project file

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/cli#233]
If you don't specify any permissions for a new Type in your project file, the first `deploy` creates default permissions for the Type.

Then, doing `deploy` again will remove these permissions again...

**Comment by sorenbs** [comment]
See https://github.com/graphcool/graphcool/issues/459

**Comment by marktani** [comment]
Needs to be verified with the latest version, now that graphcool/graphcool#459 is closed.

**Comment by timsuchanek** [comment]
Solved by the wildcard
