### ISSUE TITLE
Types.graphql should update after adding a module

### ISSUE THREAD

**Issue by Alex-Mann** [graphcool/cli#240]
When adding a module via the cli, I run `graphcool module add moduleName` and then have to run `graphcool pull` (which to my understanding will be removed in the future) to update the `types.graphcool` file.

I feel as though when you add a module, it should automatically append the type(s) specified in the module to the user's schema as long as there is no naming conflict.

**Comment by kbrandwijk** [comment]
I my experience, `graphcool module:add` adds the module to your main project file (under `modules`). The module has its own `types.graphql`. The types are not added to the main `types.graphql`.

**Comment by Alex-Mann** [comment]
@kbrandwijk Yes, that is my experience as well. I just believe it would offer a more streamlined DX if you automatically add the type specified in the module, or give the option to automatically add the type.

Reason being - if you are installing a module, you likely want to use it. In the current DX, you would not be able to use a module until after you add the type manually.

**Comment by kbrandwijk** [comment]
Ah, I understand what you mean (I think). It seems like you are referring to this: https://github.com/graphcool/graphcool-cli/issues/225 or running into this bug: https://github.com/graphcool/graphcool-cli/issues/231.

**Comment by timsuchanek** [comment]
@Alex-Mann after `graphcool module add ...` you just have to do `graphcool deploy` and the types of the module will be deployed as well. We should communicate this more clearly though

**Comment by marktani** [comment]
I hope this comment helps clarify the purpose of modules, @Alex-Mann: https://www.graph.cool/forum/t/feedback-new-cli-beta/949/22?u=nilan

Closing this 🙂
