### ISSUE TITLE
[1.3.13] 504 when graphcool init

### ISSUE THREAD

**Issue by antho1404** [graphcool/cli#241]
When I run `graphcool init` and I select an existing project, the project is well duplicated (except from the default permissions that are still present) but I don't have any files locally and I have a `GraphQL Error (Code: 504):` with some html in the response 

```
The request could not be satisfied
CloudFront attempted to establish a connection with the origin, but either the attempt failed or the origin closed the connection.
Generated by cloudfront (CloudFront)
Request ID: rl8JEy_WUocBQZTIKaUC4yXdPJ9uEhAVfUAXe_tC5WwlPAtHNNPc6Q==
```

and this seems to coming from the mutation 

```
mutation($projectId: String!, $force: Boolean, $isDryRun: Boolean!, $config: String!) {
  push(input: {
    projectId: $projectId
    force: $force
    isDryRun: $isDryRun
    config: $config
    version: 1
  }) {
...
```

I can reproduce this all the time, I don't want to put the full logs because of some private endpoints but I can send that on slack fi needed

**Comment by marktani** [comment]
Can you please do 

```

**Comment by marktani** [comment]
Looks like it's the same problem as here: https://github.com/graphcool/graphcool/issues/551

**Comment by antho1404** [comment]
Regarding the comments on the https://github.com/graphcool/graphcool/issues/551, I just tried again and it looks like even 60s is not enough, I don't have a huge project

- 11 types
- 9 SSS functions (all webhooks)
- 34 permissions

The timeout happen all the time but I was wondering maybe a solution should be to split the different call because now in one call to the `push` mutation it looks like there is all the permissions, functions, schema.

Maybe a start could be to first `push` the schema then permissions then the functions like that we push less data at the same time and I guess reduce the risk of timeouts

**Comment by marktani** [comment]
This is further discussed in https://github.com/graphcool/graphcool/issues/551.
