### ISSUE TITLE
--region parameter broken for init

### ISSUE THREAD

**Issue by marktani** [graphcool/cli#270]
![image](https://user-images.githubusercontent.com/1780597/30869937-c4880b02-a2e2-11e7-8c25-df3f67e3b2b1.png)

![image](https://user-images.githubusercontent.com/1780597/30869973-e5193a12-a2e2-11e7-9d30-0847b4ffe47d.png)

**Comment by marktani** [comment]
My bad, should have written `--region` instead of `--regions`.

**Comment by kbrandwijk** [comment]
Well, at least this deserves a related issue, as using an invalid command option (like `--regions` in this case) should not be interpreted differently (in this case, as folder name).

**Comment by marktani** [comment]
Good point! Created this one: https://github.com/graphcool/cli/issues/271
